name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: 🔨 Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world!"

      - name: Check System Uptime
        run: uptime

      - name: Show Number of CPU Cores
        run: nproc

      - name: Build Complete
        run: echo "✅ Build step finished."

  test:
    name: 🧪 Test Stage
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Test Script

