name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world!"

      - name: Check system uptime
        run: uptime

      - name: Show number of CPU cores
        run: nproc

      - name: Final build message
        run: echo "Build complete ✅"

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures test runs AFTER build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test script
        run: |
          echo "Running tests..."
          ./test.sh  # Replace with your actual test command (npm test, pytest, etc.)

      - name: Final test message
        run: echo "Test complete ✅"

